// AUTO-GENERATED by scripts/build-ar-dictionaries.ts — DO NOT EDIT BY HAND.
// Arabic player/coach names sourced from Wikidata, keyed by api-football person
// id. Treat as a draft: hand-corrections belong in `people.overrides.ar.ts`.
export const PEOPLE_AR_GENERATED: Record<number, string> = {};
