/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    authors: Author;
    articles: Article;
    competitions: Competition;
    clubs: Club;
    subscribers: Subscriber;
    pages: Page;
    redirects: Redirect;
    videos: Video;
    ads: Ad;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    competitions: CompetitionsSelect<false> | CompetitionsSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    ads: AdsSelect<false> | AdsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'fr' | 'en') | ('ar' | 'fr' | 'en')[];
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'ar' | 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Original WordPress URL - used for dedup during migration.
   */
  wpUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (ASCII, lowercase, hyphens)
   */
  slug: string;
  /**
   * Parent category for hierarchical structure
   */
  parent?: (number | null) | Category;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  social?: {
    twitter?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Auto-generated from the title (spaces become dashes), per language. Leave it blank — it fills in automatically when you save.
   */
  slug: string;
  /**
   * Short summary for cards and SEO meta description
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  /**
   * Optional external image URL fallback (used when 'featuredImage' upload is empty). Used for preview seed data.
   */
  featuredImageUrl?: string | null;
  author: number | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  status: 'draft' | 'published';
  /**
   * Leave empty — set automatically to now when you publish.
   */
  publishedAt?: string | null;
  /**
   * Mark as video article (shows YouTube embed)
   */
  isVideo?: boolean | null;
  /**
   * YouTube video URL (e.g., https://youtube.com/watch?v=...)
   */
  videoUrl?: string | null;
  /**
   * Set by the archive importer. The resume key — an existing row is skipped, never duplicated.
   */
  wpPostId?: number | null;
  /**
   * The original WordPress post_name, so old URLs resolve by exact match rather than fuzzy title comparison.
   */
  legacySlug?: string | null;
  /**
   * Drives indexation. Native articles are always indexable; archive tiers are released in batches by publish year — see lib/seo/indexation.ts. Changing the release config is a config edit, never a re-import.
   */
  seoTier?: ('editorial' | 'archive-full' | 'archive-brief') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions".
 */
export interface Competition {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Optional external logo URL fallback (used when 'logo' upload is empty). Useful for seeded preview data referencing API-Football's CDN.
   */
  logoUrl?: string | null;
  type: 'league' | 'cup';
  country?: string | null;
  /**
   * League ID from API-Football (e.g., 39 for Premier League)
   */
  apiFootballId: number;
  /**
   * Current season year (e.g., 2025 for 2025-26)
   */
  season: number;
  /**
   * Lower sorts first. Controls the homepage leagues carousel, the news-filter pills, and which competition is used by default wherever none is chosen explicitly (hero matches panel, article sidebar). Put the league currently in season at 0.
   */
  displayOrder?: number | null;
  /**
   * Links this competition to a news category for article filtering
   */
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Optional external logo URL fallback (used when 'logo' upload is empty). Useful for seeded preview data referencing API-Football's CDN.
   */
  logoUrl?: string | null;
  /**
   * Team ID from API-Football
   */
  apiFootballId?: number | null;
  competitions?: (number | Competition)[] | null;
  venue?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  locale: 'ar' | 'fr' | 'en';
  status: 'pending' | 'confirmed' | 'unsubscribed';
  confirmToken?: string | null;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL identifier: about, contact, legal, privacy
   */
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Legacy URL redirects (WordPress migration)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old path (e.g., /%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-old-slug/)
   */
  from: string;
  /**
   * New path (e.g., /ar/articles/new-slug)
   */
  to: string;
  statusCode: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * The 11-character YouTube video ID.
   */
  youtubeId: string;
  playlist: 'the-third-half' | 'from-the-stadiums';
  title: string;
  thumbnailUrl: string;
  duration?: string | null;
  publishedAt?: string | null;
  /**
   * Lower = earlier. Set from playlist order on sync.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each row is one ad creative. Multiple ads sharing a placement rotate as a slider in that slot.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads".
 */
export interface Ad {
  id: number;
  /**
   * Internal label (e.g. 'OCP SIAM — June').
   */
  name: string;
  /**
   * Image = upload a creative. Ad-manager tag = paste an embed snippet from your network (Google Ad Manager, AdSense, etc.) and it fills the slot automatically.
   */
  type: 'image' | 'tag';
  /**
   * Banners: design ~1600×376 (wide). News cards: design 16:9 (e.g. 600×400). Article side rail: design 300×600 (vertical). Only used for Image-type ads.
   */
  image?: (number | null) | Media;
  /**
   * Optional. Paste the part of the snippet that belongs in the page <head> (the loader/script). Loaded once site-wide; identical headers across ads load only once. Leave empty if your snippet is body-only.
   */
  headCode?: string | null;
  /**
   * Paste the part placed where the ad appears (the unit markup, e.g. the <ins>/<script> push). The network fills it. Leave Image empty for tag ads.
   */
  embedCode?: string | null;
  /**
   * Optional. Clicking the ad opens this in a new tab.
   */
  linkUrl?: string | null;
  placement: 'top-banner' | 'hero-news' | 'news-videos' | 'videos-matches' | 'news-card' | 'article-sidebar';
  /**
   * Uncheck to hide without deleting.
   */
  active?: boolean | null;
  /**
   * Lower shows first in the slider rotation.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'competitions';
        value: number | Competition;
      } | null)
    | ({
        relationTo: 'clubs';
        value: number | Club;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'ads';
        value: number | Ad;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  wpUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  social?:
    | T
    | {
        twitter?: T;
        facebook?: T;
        instagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  featuredImage?: T;
  featuredImageUrl?: T;
  author?: T;
  categories?: T;
  tags?: T;
  status?: T;
  publishedAt?: T;
  isVideo?: T;
  videoUrl?: T;
  wpPostId?: T;
  legacySlug?: T;
  seoTier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "competitions_select".
 */
export interface CompetitionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoUrl?: T;
  type?: T;
  country?: T;
  apiFootballId?: T;
  season?: T;
  displayOrder?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoUrl?: T;
  apiFootballId?: T;
  competitions?: T;
  venue?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  status?: T;
  confirmToken?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  youtubeId?: T;
  playlist?: T;
  title?: T;
  thumbnailUrl?: T;
  duration?: T;
  publishedAt?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ads_select".
 */
export interface AdsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  image?: T;
  headCode?: T;
  embedCode?: T;
  linkUrl?: T;
  placement?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Control the homepage news filter, which matches show in the hero and lower match sections, and the matches calendar on article pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The pills in the 'News by league' section, top to bottom. Each pill shows a competition's crest/name and lists articles carrying the chosen tag.
   */
  newsFilters?:
    | {
        /**
         * Provides the pill's crest and name.
         */
        competition: number | Competition;
        /**
         * Articles with this tag fill this tab. If empty (or none yet), the tab falls back to the competition's linked category.
         */
        tag?: (number | null) | Tag;
        id?: string | null;
      }[]
    | null;
  heroMatches?: {
    /**
     * Its fixtures (finished, live, upcoming) fill the hero matches panel. Leave empty to use the competition with the lowest display order.
     */
    competition?: (number | null) | Competition;
  };
  homeMatches: {
    mode: 'today' | 'competition';
    /**
     * Shown when Source is 'A specific competition'.
     */
    competition?: (number | null) | Competition;
  };
  /**
   * The matches calendar in the right rail of every article page.
   */
  articleMatches?: {
    enabled?: boolean | null;
    /**
     * Its upcoming fixtures fill the calendar, and its name is the card's heading. Leave empty to use the competition with the lowest display order.
     */
    competition?: (number | null) | Competition;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  newsFilters?:
    | T
    | {
        competition?: T;
        tag?: T;
        id?: T;
      };
  heroMatches?:
    | T
    | {
        competition?: T;
      };
  homeMatches?:
    | T
    | {
        mode?: T;
        competition?: T;
      };
  articleMatches?:
    | T
    | {
        enabled?: T;
        competition?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialEmbedBlock".
 */
export interface SocialEmbedBlock {
  /**
   * Paste the post's link, or the embed code copied from Facebook, X, Instagram or YouTube — either works. It is cleaned up to a plain link automatically when you save.
   */
  source: string;
  /**
   * Shown beneath the embed to every reader — this is not an internal note. A deleted post, a private account, or a suspended one all still return a normal page and render nothing, and that can't be detected from the server, so this caption (plus a link to the original post) is what a reader sees when the embed itself doesn't load.
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'socialEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Add two or more images. They appear in the order you set here, and each can carry its own caption.
   */
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * How the gallery is displayed on the article page.
   */
  layout: 'grid' | 'carousel';
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudioBlock".
 */
export interface AudioBlock {
  /**
   * Upload an MP3 the same way you upload a photo. A player appears in the article wherever you place this block.
   */
  file: number | Media;
  /**
   * Optional — shown above the player, e.g. "Full post-match interview".
   */
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'audio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedFrameBlock".
 */
export interface EmbedFrameBlock {
  /**
   * Only links from Datawrapper, Google Maps, SoundCloud or Spotify are accepted.
   */
  src: string;
  /**
   * Frame height in pixels. 400 suits most maps and charts; a SoundCloud player is usually shorter (around 166).
   */
  height: number;
  /**
   * Required. Describes the frame's content for screen-reader users — an iframe with no accessible name is unusable with a screen reader. Not shown visually.
   */
  title: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embedFrame';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}